version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - ./secrets:/app/secrets:ro
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped